/**
 * Обширная база заданий. Каждая запись — готовый контент для одной механики на конкретном месте.
 * Сборщик квеста берёт не больше одного задания на mechanicId и не повторяет placeId в маршруте.
 */
window.QUEST_DB = {
  version: 2,
  zones: {
    garden: { label: "Садовое кольцо", tasks: 5 },
    ttk: { label: "ТТК", tasks: 10 },
  },
  places: {
    griboedov: {
      name: "Памятник А. С. Грибоедову",
      address: "Чистопрудный бульвар",
      zone: "ttk",
      lat: 55.7609,
      lon: 37.6436,
    },
    pushkin: {
      name: "Памятник А. С. Пушкину",
      address: "Пушкинская площадь",
      zone: "garden",
      lat: 55.7652,
      lon: 37.604,
    },
    chistye_east: {
      name: "Чистый пруд · восточный берег",
      address: "у воды, Чистопрудный бульвар",
      zone: "ttk",
      lat: 55.7602,
      lon: 37.6455,
    },
    pokrovka_facade: {
      name: "Доходный дом на Покровке",
      address: "ул. Покровка (кластер у бульвара)",
      zone: "ttk",
      lat: 55.7591,
      lon: 37.6468,
    },
    navoi: {
      name: "Памятник Алишеру Навои",
      address: "Чистопрудный бульвар",
      zone: "ttk",
      lat: 55.7596,
      lon: 37.6461,
    },
    chistye_bench: {
      name: "Скамья у Чистого пруда",
      address: "восточная сторона",
      zone: "ttk",
      lat: 55.7601,
      lon: 37.645,
    },
    boulevard_lanterns: {
      name: "Фонарная линия бульвара",
      address: "Чистопрудный бульвар",
      zone: "ttk",
      lat: 55.7605,
      lon: 37.6448,
    },
    year_house: {
      name: "Дом с датой на фасаде",
      address: "переулок у Покровки",
      zone: "ttk",
      lat: 55.7588,
      lon: 37.6482,
    },
    metro_panel: {
      name: "Публичное панно у выхода",
      address: "кластер Чистых прудов",
      zone: "ttk",
      lat: 55.762,
      lon: 37.641,
    },
    plaque_boulevard: {
      name: "Мемориальная доска у бульвара",
      address: "Чистопрудный бульвар",
      zone: "ttk",
      lat: 55.7614,
      lon: 37.6421,
    },
    patriarch: {
      name: "Патриаршие пруды · беседка/берег",
      address: "Малая Бронная / пруды",
      zone: "garden",
      lat: 55.7636,
      lon: 37.5925,
    },
    mayakovsky: {
      name: "Памятник В. В. Маяковскому",
      address: "Триумфальная площадь",
      zone: "garden",
      lat: 55.7697,
      lon: 37.5959,
    },
    nikitsky_gate: {
      name: "Никитские ворота · ротонда",
      address: "площадь Никитские Ворота",
      zone: "garden",
      lat: 55.7578,
      lon: 37.5995,
    },
    twer_boulevard: {
      name: "Тверской бульвар · начало",
      address: "у памятника Тимирязеву / начало бульвара",
      zone: "garden",
      lat: 55.7589,
      lon: 37.5978,
    },
    courtyard_lane: {
      name: "Тихий двор у Покровки",
      address: "арка / двор (общедоступный)",
      zone: "ttk",
      lat: 55.7585,
      lon: 37.6475,
    },
    viewpoint_bridge: {
      name: "Видовая точка у пруда",
      address: "мостик / проход у воды",
      zone: "ttk",
      lat: 55.7604,
      lon: 37.6445,
    },
  },

  tasks: [
    /* —— CONTOUR —— */
    {
      id: "t_contour_griboedov",
      mechanicId: "contour_camera",
      placeId: "griboedov",
      difficulty: ["medium", "hard"],
      title: "Совместите контур с памятником",
      hint: "Дипломат и автор «Горя от ума». На экране — живое фото с выделением объекта. Найдите тот же памятник и совместите контур: стоящая фигура, плащ, постамент с рельефом.",
      ui: "contour",
      photoKey: "griboedov",
      contourHint: "Выделение снято с реального фото Wikimedia: стоящий человек на высоком постаменте.",
      fallbackQuestion: "Скульптура стоит или сидит?",
      fallbackAnswer: "стоит",
      fact: "Контур снят с фото памятника Грибоедову на Чистопрудном (Wikimedia Commons).",
    },
    {
      id: "t_contour_pushkin",
      mechanicId: "contour_camera",
      placeId: "pushkin",
      difficulty: ["medium", "hard"],
      title: "Контур Пушкина",
      hint: "На экране — живое фото Пушкина с контуром-выделением. Совместите с памятником на площади: фигура в сюртуке, рука у борта, высокий постамент.",
      ui: "contour",
      photoKey: "pushkin",
      contourHint: "Узнаваемые черты: наклон головы, сюртук, высокий гранитный постамент.",
      fallbackQuestion: "Одна рука у Пушкина спрятана в борт сюртука — да или нет?",
      fallbackAnswer: "да",
      fact: "Контур снят с фото памятника Пушкину на Пушкинской площади (Wikimedia Commons).",
    },
    {
      id: "t_contour_seated_tver",
      mechanicId: "contour_camera",
      placeId: "twer_boulevard",
      difficulty: ["medium", "hard"],
      title: "Сидящий силуэт",
      hint: "Пока используем схемный контур сидящей фигуры (живое фото добавим следующим). Найдите сидящий памятник у начала Тверского бульвара.",
      ui: "contour",
      photoKey: null,
      contourAsset: "contour_seated",
      contourHint: "Сидит — контур шире внизу.",
      fallbackQuestion: "Памятник сидячий или стоячий?",
      fallbackAnswer: "сидячий",
      fact: "Сидящие памятники дают другой контур, чем стоящие фигуры Грибоедова или Пушкина.",
    },

    /* —— GEO —— */
    {
      id: "t_geo_chistye",
      mechanicId: "geo_safe",
      placeId: "chistye_east",
      difficulty: ["easy", "medium", "hard"],
      title: "Гео-сейф у воды",
      hint: "Подойдите к восточному берегу пруда. Пока вы далеко — следующая сцена закрыта.",
      ui: "geo",
      radiusM: 30,
      lockedTeaser: "Сейф молчит, пока вы не у воды…",
      unlockedText: "Сейф открыт. Дальше ищите на Покровке деталь фасада — кроп уже ждёт в следующем задании.",
      fact: "Чистые пруды — один пруд; множественное число в названии — исторический след.",
    },
    {
      id: "t_geo_patriarch",
      mechanicId: "geo_safe",
      placeId: "patriarch",
      difficulty: ["easy", "medium", "hard"],
      title: "Сейф Патриарших",
      hint: "Войдите в радиус у берега Патриарших прудов.",
      ui: "geo",
      radiusM: 35,
      lockedTeaser: "Литературный пруд не открывает подсказку издалека.",
      unlockedText: "Открыто. Дальше — внимательно смотрите на детали вокруг бульвара.",
      fact: "Патриаршие — компактная «литературная» точка внутри Садового.",
    },
    {
      id: "t_geo_mayakovsky",
      mechanicId: "geo_safe",
      placeId: "mayakovsky",
      difficulty: ["easy", "medium", "hard"],
      title: "Сейф у Маяковского",
      hint: "Подойдите к памятнику на Триумфальной — только там откроется ключ маршрута.",
      ui: "geo",
      radiusM: 25,
      lockedTeaser: "«А вы ноктюрн сыграть могли бы…» — но не с того расстояния.",
      unlockedText: "Сейф открыт. Следующая точка — наблюдательность на фасадах и табличках.",
      fact: "Площадь у Маяковского удобна как якорная гео-точка Садового кольца.",
    },

    /* —— FIND DETAIL —— */
    {
      id: "t_detail_lion",
      mechanicId: "find_detail",
      placeId: "pokrovka_facade",
      difficulty: ["easy", "medium", "hard"],
      title: "Найдите этот фрагмент на фасаде",
      hint: "На экране — кроп каменного декора, как вырезанный кусок фото. Найдите тот же элемент на реальном доме и выберите, что это.",
      ui: "detail",
      cropAsset: "crop_lion_mascaron",
      cropCaption: "Кроп фасада (без подписи). Сверьте с домом.",
      options: ["Львиный маскарон", "Атлант с капителью", "Советский герб", "Мозаичный медальон"],
      correctIndex: 0,
      fact: "Маскароны львов часто украшали доходные дома рубежа XIX–XX вв. — их ищут глазами, а не по эмодзи.",
    },
    {
      id: "t_detail_atlant",
      mechanicId: "find_detail",
      placeId: "nikitsky_gate",
      difficulty: ["medium", "hard"],
      title: "Фрагмент скульптуры",
      hint: "Сверьте кроп с окружением площади / декора ротонды и соседних фасадов.",
      ui: "detail",
      cropAsset: "crop_atlant_hand",
      cropCaption: "Кроп: фрагмент фигуры",
      options: ["Фрагмент атланта / кариатиды", "Фонарный кронштейн", "Домовая табличка", "Вентиляционная решётка"],
      correctIndex: 0,
      fact: "Атланты и кариатиды «держат» карниз — характерный приём эклектики и классицизма.",
    },
    {
      id: "t_detail_leaf",
      mechanicId: "find_detail",
      placeId: "courtyard_lane",
      difficulty: ["easy", "medium"],
      title: "Деталь в тихом дворе",
      hint: "Зайдите в общедоступный двор/арку и найдите декоративный элемент как на кропе.",
      ui: "detail",
      cropAsset: "crop_wrought_leaf",
      cropCaption: "Кроп металлического / лепного декора",
      options: ["Лист / растительный завиток", "Цифра года", "Герб Москвы", "Камера наблюдения"],
      correctIndex: 0,
      fact: "Дворовые детали часто интереснее парадного фасада — отсюда механика «тихий двор».",
    },

    /* —— PLAQUE —— */
    {
      id: "t_plaque_1959",
      mechanicId: "plaque_scan",
      placeId: "plaque_boulevard",
      difficulty: ["easy", "medium"],
      title: "Год на табличке",
      hint: "Найдите мемориальную или информационную табличку у памятника/дома и введите год.",
      ui: "plaque",
      prompt: "Введите год с таблички",
      expected: "1959",
      alternatives: ["1959 г", "1959г.", "1959 г."],
      fact: "Год на доске — быстрый якорь: установка памятника или годы жизни.",
    },
    {
      id: "t_plaque_pushkin_year",
      mechanicId: "plaque_scan",
      placeId: "pushkin",
      difficulty: ["easy", "medium"],
      title: "Табличка у Пушкина",
      hint: "Считайте год с информационной таблички у памятника (демо-ответ для превью).",
      ui: "plaque",
      prompt: "Год установки (демо)",
      expected: "1880",
      alternatives: ["1880 г", "1880г"],
      fact: "Оригинальный памятник Пушкину открыли в 1880 году (позже переносили).",
    },

    /* —— COUNT —— */
    {
      id: "t_count_lanterns",
      mechanicId: "count_elements",
      placeId: "boulevard_lanterns",
      difficulty: ["medium", "hard"],
      title: "Сосчитайте фонари",
      hint: "На отрезке бульвара вдоль воды сосчитайте фонари по одной стороне (демо-ответ 6, допуск ±1).",
      ui: "count",
      prompt: "Число фонарей",
      correctNumber: 6,
      tolerance: 1,
      fact: "Счёт заставляет смотреть на бульвар как на композицию, а не фон.",
    },
    {
      id: "t_count_steps",
      mechanicId: "count_elements",
      placeId: "pushkin",
      difficulty: ["medium", "hard"],
      title: "Ступени постамента",
      hint: "Сколько ярусных уступов/ступеней у постамента со стороны главного подхода? (демо: 3)",
      ui: "count",
      prompt: "Число ярусов",
      correctNumber: 3,
      tolerance: 0,
      fact: "Постамент — часть памятника; его тоже «читают» глазами.",
    },

    /* —— YEAR KEY —— */
    {
      id: "t_year_1903",
      mechanicId: "year_key",
      placeId: "year_house",
      difficulty: ["easy", "medium"],
      title: "Год-ключ на фасаде",
      hint: "Найдите дату на картуше/фасаде. Этот год откроет следующую точку.",
      ui: "year",
      prompt: "Введите год",
      expected: "1903",
      fact: "1903 — типичный якорь эпохи модерна в московской застройке.",
    },
    {
      id: "t_year_patriarch",
      mechanicId: "year_key",
      placeId: "patriarch",
      difficulty: ["easy", "medium"],
      title: "Ключ у пруда",
      hint: "Найдите год на ближайшей табличке/информационном стенде (демо-ключ 1925 для превью маршрута).",
      ui: "year",
      prompt: "Год-ключ",
      expected: "1925",
      fact: "Годы на стендах помогают связать место с культурным слоем эпохи.",
    },

    /* —— ART PUZZLE —— */
    {
      id: "t_puzzle_panel",
      mechanicId: "art_puzzle",
      placeId: "metro_panel",
      difficulty: ["easy", "medium"],
      title: "Соберите панно",
      hint: "Рядом с публичным изображением соберите пазл: куски — фрагменты одного сюжета. Смотрите на оригинал, если застряли.",
      ui: "puzzle",
      puzzleTiles: [
        { id: "a", label: "небо", color: "#5a6a78" },
        { id: "b", label: "купол", color: "#c4a35a" },
        { id: "c", label: "вода", color: "#4a6a7a" },
        { id: "d", label: "дерево", color: "#4f6a48" },
        { id: "e", label: "фигура", color: "#8a6a55" },
        { id: "f", label: "рамка", color: "#6a5a48" },
      ],
      fact: "Пазл у оригинала связывает игру с реальным объектом — без эмодзи-подсказок.",
    },

    /* —— GUESS ROLE —— */
    {
      id: "t_role_navoi",
      mechanicId: "guess_role",
      placeId: "navoi",
      difficulty: ["easy", "medium"],
      title: "Кто этот герой?",
      hint: "Посмотрите на памятник и подпись. Выберите роль.",
      ui: "quiz",
      question: "Кем был Алишер Навои?",
      options: ["Поэт и мыслитель", "Полководец Орды", "Московский купец", "Архитектор метро"],
      correctIndex: 0,
      fact: "Навои — великий тюркский поэт XV века; памятник на Чистопрудном — знак культурных связей.",
    },
    {
      id: "t_role_mayakovsky",
      mechanicId: "guess_role",
      placeId: "mayakovsky",
      difficulty: ["easy", "medium"],
      title: "Роль Маяковского",
      hint: "Определите главную роль героя памятника.",
      ui: "quiz",
      question: "Владимир Маяковский прежде всего…",
      options: ["Поэт", "Полководец", "Композитор", "Живописец-передвижник"],
      correctIndex: 0,
      fact: "Маяковский — поэт футуризма и советской эпохи; памятник держит площадь как культурный якорь.",
    },
    {
      id: "t_role_griboedov",
      mechanicId: "guess_role",
      placeId: "griboedov",
      difficulty: ["easy", "medium"],
      title: "Роль Грибоедова",
      hint: "Если уже видели памятник — закрепите смысл.",
      ui: "quiz",
      question: "Грибоедов известен как…",
      options: ["Драматург и дипломат", "Только полководец 1812 года", "Основатель университета", "Художник-иконописец"],
      correctIndex: 0,
      fact: "«Горе от ума» и дипломатическая служба — две линии одной биографии.",
    },

    /* —— MYTH —— */
    {
      id: "t_myth_chistye",
      mechanicId: "myth_or_fact",
      placeId: "chistye_bench",
      difficulty: ["easy", "medium"],
      title: "Миф или факт у пруда",
      hint: "Отметьте каждое утверждение.",
      ui: "myth",
      statements: [
        { text: "Чистые пруды — это один пруд, а не сеть прудов.", truth: true },
        { text: "Зимой по пруду ежедневно ходят рейсовые пароходы с оркестром.", truth: false },
        { text: "Название связано с очищением местности от «грязных» ремёсел.", truth: true },
      ],
      fact: "Легенды запоминаются лучше справки — если потом показать, где миф.",
    },
    {
      id: "t_myth_patriarch",
      mechanicId: "myth_or_fact",
      placeId: "patriarch",
      difficulty: ["easy", "medium"],
      title: "Мифы Патриарших",
      hint: "Правда или городская легенда?",
      ui: "myth",
      statements: [
        { text: "Патриаршие пруды описаны в «Мастере и Маргарите».", truth: true },
        { text: "Пруды названы в честь патриарха, жившего здесь в XX веке как мэр Москвы.", truth: false },
        { text: "Место долго было литературным и «гулятельным» центром.", truth: true },
      ],
      fact: "Булгаков сделал Патриаршие частью мирового культурного кода Москвы.",
    },

    /* —— FINALE —— */
    {
      id: "t_finale_chistye",
      mechanicId: "finale_synthesis",
      placeId: "chistye_bench",
      difficulty: ["medium", "hard"],
      title: "Смысл маршрута",
      hint: "Соберите впечатление от всей прогулки.",
      ui: "finale",
      question: "Какой мотив доминировал?",
      options: [
        "Бульвар, вода и памятники культуры",
        "Только сталинские высотки",
        "Промышленные зоны у ТТК",
        "Только храмы XVII века",
      ],
      correctIndex: 0,
      fact: "Финал превращает набор точек в историю, а не в чекины.",
    },
    {
      id: "t_finale_garden",
      mechanicId: "finale_synthesis",
      placeId: "pushkin",
      difficulty: ["medium", "hard"],
      title: "Итог Садового",
      hint: "Что связывало точки внутри Садового кольца?",
      ui: "finale",
      question: "Главная нить прогулки?",
      options: [
        "Литература и городские памятники в плотном центре",
        "Усадьбы за МКАД",
        "Только метро-мозаики 1970-х",
        "Спортивные арены",
      ],
      correctIndex: 0,
      fact: "Садовое кольцо удобно для коротких литературно-архитектурных петель.",
    },

    /* —— THEN AND NOW / EXTRA for variety —— */
    {
      id: "t_era_pokrovka",
      mechanicId: "era_style",
      placeId: "pokrovka_facade",
      difficulty: ["medium", "hard"],
      title: "Эпоха дома",
      hint: "По фасаду определите стиль эпохи.",
      ui: "quiz",
      question: "Ближе всего стиль доходного дома:",
      options: ["Эклектика / модерн рубежа веков", "Конструктивизм 1920-х", "Лужковский стиль 1990-х", "Древнерусский XVII век"],
      correctIndex: 0,
      fact: "Покровка сохраняет слой доходных домов с богатым декором.",
    },
    {
      id: "t_word_facade",
      mechanicId: "word_from_facade",
      placeId: "year_house",
      difficulty: ["medium", "hard"],
      title: "Слово с фасада",
      hint: "Считайте короткое слово или аббревиатуру с картуша (демо-ответ: ДОМ).",
      ui: "plaque",
      prompt: "Введите слово",
      expected: "дом",
      alternatives: ["ДОМ", "Дом"],
      fact: "Иногда на фасаде буквально написана подсказка — её легко пропустить.",
    },
    {
      id: "t_viewpoint",
      mechanicId: "viewpoint_station",
      placeId: "viewpoint_bridge",
      difficulty: ["easy", "medium"],
      title: "Видовая станция",
      hint: "Встаньте у воды так, чтобы в кадре одновременно были пруд и линия фонарей. Ответьте на вопрос.",
      ui: "quiz",
      question: "Что важнее для этой точки?",
      options: ["Ракурс на воду и бульвар", "Подземный переход", "Парковка", "Рекламный щит"],
      correctIndex: 0,
      fact: "Видовая точка учит «ставить кадр» городу, а не только чекиниться.",
    },
    {
      id: "t_circle_griboedov",
      mechanicId: "circle_object",
      placeId: "griboedov",
      difficulty: ["easy", "medium"],
      title: "Обойдите памятник",
      hint: "Отметьте три стороны: лицо, профиль, спина/тыл постамента (демо — три кнопки).",
      ui: "circle",
      checkpoints: ["Лицо / фасад", "Профиль", "Тыл"],
      fact: "Обход заставляет увидеть памятник объёмно.",
    },
    {
      id: "t_restore_navoi",
      mechanicId: "restore_caption",
      placeId: "navoi",
      difficulty: ["medium", "hard"],
      title: "Восстановите подпись",
      hint: "Подпись с пропусками — восстановите по памятнику.",
      ui: "plaque",
      prompt: "Алишер ____",
      expected: "навои",
      alternatives: ["Навои", "НАВОИ"],
      fact: "Имя на постаменте — часть культурного жеста места.",
    },
    {
      id: "t_link_poets",
      mechanicId: "link_two_heroes",
      placeId: "chistye_bench",
      difficulty: ["medium", "hard"],
      title: "Связь героев",
      hint: "Какая связь ближе между Грибоедовым и Пушкиным в контексте маршрута?",
      ui: "quiz",
      question: "Их связывает прежде всего…",
      options: [
        "Литературный век и культура Москвы",
        "Общий полководецский чин 1812 года",
        "Строительство метро",
        "Живопись передвижников",
      ],
      correctIndex: 0,
      fact: "Связки между точками делают квест историей, а не списком адресов.",
    },
    {
      id: "t_quote_pushkin",
      mechanicId: "quote_detective",
      placeId: "pushkin",
      difficulty: ["medium", "hard"],
      title: "Цитата-детектив",
      hint: "«Я памятник себе воздвиг нерукотворный…» — к кому/чему ведёт эта линия в городе? Дойдите до памятника поэту.",
      ui: "quiz",
      question: "Куда ведёт цитата в этой прогулке?",
      options: ["К памятнику Пушкину", "К Третьяковской галерее", "К Останкинской башне", "К ВДНХ"],
      correctIndex: 0,
      fact: "Цитата работает как компас смысла, даже если GPS уже привёл вас сюда.",
    },
    {
      id: "t_fact_mosaic",
      mechanicId: "fact_mosaic",
      placeId: "chistye_bench",
      difficulty: ["easy", "medium"],
      title: "Мозаика фактов",
      hint: "Сопоставьте факт и объект.",
      ui: "mosaic",
      pairs: [
        { fact: "Автор «Горя от ума»", target: "Грибоедов" },
        { fact: "Один пруд с «множественным» именем", target: "Чистые пруды" },
        { fact: "Поэт XV века, памятник на бульваре", target: "Навои" },
      ],
      shuffleTargets: ["Навои", "Грибоедов", "Чистые пруды", "Маяковский"],
      fact: "Короткая мозаика закрепляет маршрут в памяти.",
    },
  ],
};
