/** Default export recipe — 10 точек из пула 15 механик */
window.DEMO_EXPORT = {
  zone: "ttk",
  difficulty: "medium",
  enabledMechanics: [
    "contour_camera",
    "geo_safe",
    "find_detail",
    "plaque_scan",
    "year_key",
    "count_elements",
    "art_puzzle",
    "guess_role",
    "myth_or_fact",
    "era_style",
    "quote_detective",
    "word_from_facade",
    "restore_caption",
    "link_two_heroes",
    "finale_synthesis",
  ],
  disabledMechanics: [],
  questDraft: {
    taskCount: 10,
    mechanics: [
      { slot: 1, id: "contour_camera", name: "Контур на камере", uniqueFeature: true },
      { slot: 2, id: "geo_safe", name: "Гео-сейф", uniqueFeature: true },
      { slot: 3, id: "find_detail", name: "Найди деталь", uniqueFeature: false },
      { slot: 4, id: "plaque_scan", name: "Табличка", uniqueFeature: false },
      { slot: 5, id: "count_elements", name: "Посчитай элементы", uniqueFeature: false },
      { slot: 6, id: "year_key", name: "Год-ключ", uniqueFeature: false },
      { slot: 7, id: "guess_role", name: "Роль героя", uniqueFeature: false },
      { slot: 8, id: "myth_or_fact", name: "Миф или факт", uniqueFeature: false },
      { slot: 9, id: "era_style", name: "Эпоха и стиль", uniqueFeature: false },
      { slot: 10, id: "finale_synthesis", name: "Финал маршрута", uniqueFeature: false },
    ],
  },
};
