/**
 * 15 механик v1 — интересные, с вопросами, без тяжёлого AR (кроме 1 контура).
 * Фишки: contour_camera ≤1, geo_safe ≤1 на квест.
 */
window.MECHANICS_DB = {
  version: 2,
  updated: "2026-09-15",
  rules: {
    uniqueFeatureMaxPerQuest: {
      contour_camera: 1,
      geo_safe: 1,
    },
    zones: {
      garden: { label: "Садовое кольцо", tasks: 5 },
      ttk: { label: "ТТК", tasks: 10 },
    },
    difficulties: ["easy", "medium", "hard"],
    coreShare: "80% обычные механики, по 10% слои A и C",
  },
  mechanics: [
    {
      id: "contour_camera",
      num: 1,
      name: "Контур на камере",
      group: "unique",
      uniqueFeature: true,
      featureKey: "contour_camera",
      tags: ["cam", "ar", "quiz"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: true,
      needsAsset: ["silhouette_key", "guess_options", "fallback_question"],
      placeTypes: ["monument"],
      defaultEnabled: true,
      mvp: true,
      effort: "high",
      short: "Угадай памятник по внешнему контуру, затем совмести контур в камере.",
    },
    {
      id: "geo_safe",
      num: 2,
      name: "Гео-сейф",
      group: "unique",
      uniqueFeature: true,
      featureKey: "geo_safe",
      tags: ["geo"],
      difficulties: ["easy", "medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["radius_m", "locked_content"],
      placeTypes: ["any"],
      defaultEnabled: true,
      mvp: true,
      effort: "medium",
      short: "Подсказка открывается только на месте.",
    },
    {
      id: "find_detail",
      num: 3,
      name: "Найди деталь",
      group: "visual",
      uniqueFeature: false,
      tags: ["quiz", "geo"],
      difficulties: ["easy", "medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["crop_image", "options"],
      placeTypes: ["monument", "building", "facade"],
      defaultEnabled: true,
      mvp: true,
      effort: "medium",
      short: "По кропу фасада найди элемент и ответь, что это.",
    },
    {
      id: "plaque_scan",
      num: 4,
      name: "Табличка",
      group: "text",
      uniqueFeature: false,
      tags: ["text", "geo"],
      difficulties: ["easy", "medium"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["expected_text"],
      placeTypes: ["plaque", "monument"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Считай год или фамилию с мемориальной доски.",
    },
    {
      id: "year_key",
      num: 5,
      name: "Год-ключ",
      group: "text",
      uniqueFeature: false,
      tags: ["text", "geo"],
      difficulties: ["easy", "medium"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["year"],
      placeTypes: ["building", "plaque"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Найди год на фасаде — он открывает следующую точку.",
    },
    {
      id: "count_elements",
      num: 6,
      name: "Посчитай элементы",
      group: "visual",
      uniqueFeature: false,
      tags: ["count", "geo"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["number", "tolerance"],
      placeTypes: ["building", "monument", "park"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Сосчитай колонны, фонари или ступени.",
    },
    {
      id: "art_puzzle",
      num: 7,
      name: "Пазл панно",
      group: "puzzle",
      uniqueFeature: false,
      tags: ["puzzle"],
      difficulties: ["easy", "medium"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["puzzle_tiles"],
      placeTypes: ["art", "metro", "park"],
      defaultEnabled: true,
      mvp: true,
      effort: "medium",
      short: "Собери цифровой пазл рядом с публичным изображением.",
    },
    {
      id: "guess_role",
      num: 8,
      name: "Роль героя",
      group: "meaning",
      uniqueFeature: false,
      tags: ["quiz"],
      difficulties: ["easy", "medium"],
      needsOnSite: false,
      needsCamera: false,
      needsAsset: ["options"],
      placeTypes: ["monument"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Кем был человек / чему посвящён памятник.",
    },
    {
      id: "myth_or_fact",
      num: 9,
      name: "Миф или факт",
      group: "meaning",
      uniqueFeature: false,
      tags: ["quiz"],
      difficulties: ["easy", "medium"],
      needsOnSite: false,
      needsCamera: false,
      needsAsset: ["statements"],
      placeTypes: ["any"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Отметь правду и городские легенды.",
    },
    {
      id: "era_style",
      num: 10,
      name: "Эпоха и стиль",
      group: "meaning",
      uniqueFeature: false,
      tags: ["quiz"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["options"],
      placeTypes: ["building", "monument"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Определи стиль здания или памятника.",
    },
    {
      id: "quote_detective",
      num: 11,
      name: "Цитата-детектив",
      group: "text",
      uniqueFeature: false,
      tags: ["quiz", "geo"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["quote", "options"],
      placeTypes: ["monument", "square"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "По цитате пойми, к какому месту идти.",
    },
    {
      id: "word_from_facade",
      num: 12,
      name: "Слово с фасада",
      group: "text",
      uniqueFeature: false,
      tags: ["text", "geo"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["expected_text"],
      placeTypes: ["building", "facade"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Считай слово или дату с фасада.",
    },
    {
      id: "restore_caption",
      num: 13,
      name: "Восстанови подпись",
      group: "puzzle",
      uniqueFeature: false,
      tags: ["text", "quiz"],
      difficulties: ["medium", "hard"],
      needsOnSite: true,
      needsCamera: false,
      needsAsset: ["prompt", "expected"],
      placeTypes: ["monument", "plaque"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Заполни пропуски в названии по объекту.",
    },
    {
      id: "link_two_heroes",
      num: 14,
      name: "Связь героев",
      group: "meaning",
      uniqueFeature: false,
      tags: ["quiz"],
      difficulties: ["medium", "hard"],
      needsOnSite: false,
      needsCamera: false,
      needsAsset: ["options"],
      placeTypes: ["monument", "route"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Как связаны две точки маршрута.",
    },
    {
      id: "finale_synthesis",
      num: 15,
      name: "Финал маршрута",
      group: "meaning",
      uniqueFeature: false,
      tags: ["quiz", "finale"],
      difficulties: ["medium", "hard"],
      needsOnSite: false,
      needsCamera: false,
      needsAsset: ["options"],
      placeTypes: ["any"],
      defaultEnabled: true,
      mvp: true,
      effort: "low",
      short: "Вопрос, собирающий смысл всей прогулки.",
    },
  ],
};

window.MECHANICS_CORE_15 = window.MECHANICS_DB.mechanics;
