window.MECHANICS_DB = {
  "version": 1,
  "updated": "2026-09-15",
  "rules": {
    "uniqueFeatureMaxPerQuest": {
      "contour_camera": 1,
      "geo_safe": 1
    },
    "zones": {
      "garden": { "label": "Садовое кольцо", "tasks": 5 },
      "ttk": { "label": "ТТК", "tasks": 10 }
    },
    "difficulties": ["easy", "medium", "hard"],
    "coreShare": "80% обычные механики, по 10% слои A и C"
  },
  "mechanics": [
    {
      "id": "contour_camera",
      "num": 1,
      "name": "Контур на камере",
      "group": "unique",
      "uniqueFeature": true,
      "featureKey": "contour_camera",
      "tags": ["cam", "geo", "ar"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": true,
      "needsAsset": ["contour_svg", "hint_text", "fallback_question"],
      "placeTypes": ["monument", "building", "facade"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "high",
      "short": "Совместить контур объекта с реальным видом в камере."
    },
    {
      "id": "geo_safe",
      "num": 2,
      "name": "Гео-сейф",
      "group": "unique",
      "uniqueFeature": true,
      "featureKey": "geo_safe",
      "tags": ["geo"],
      "difficulties": ["easy", "medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["radius_m", "locked_content"],
      "placeTypes": ["any"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "medium",
      "short": "Крупная подсказка или сцена открывается только в радиусе точки."
    },
    {
      "id": "find_detail",
      "num": 3,
      "name": "Найди деталь",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["cam", "quiz", "geo"],
      "difficulties": ["easy", "medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["crop_image", "answer_mode"],
      "placeTypes": ["monument", "building", "facade", "plaque"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "medium",
      "short": "По кропу найти фрагмент на реальном объекте."
    },
    {
      "id": "then_and_now",
      "num": 4,
      "name": "Тогда и сейчас",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["cam", "quiz", "geo"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["old_photo", "differences_or_viewpoint"],
      "placeTypes": ["viewpoint", "square", "street", "building"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "high",
      "short": "Сравнить старое фото с нынешним видом или встать в тот же ракурс."
    },
    {
      "id": "color_beacon",
      "num": 5,
      "name": "Цветовой маяк",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["quiz", "geo"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["palette_or_swatch", "candidates"],
      "placeTypes": ["building", "facade", "park"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "low",
      "short": "Найти объект нужного цвета среди кандидатов."
    },
    {
      "id": "silhouette_pick",
      "num": 6,
      "name": "Силуэт среди силуэтов",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["silhouette_set", "correct_id"],
      "placeTypes": ["monument", "building", "dome"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "Выбрать верный силуэт объекта из нескольких."
    },
    {
      "id": "plaque_scan",
      "num": 7,
      "name": "Скан / ввод с таблички",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["cam", "geo", "text"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": true,
      "needsAsset": ["expected_tokens", "input_mode"],
      "placeTypes": ["plaque", "building"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "medium",
      "short": "Считать год, фамилию или фразу с мемориальной таблички."
    },
    {
      "id": "count_elements",
      "num": 8,
      "name": "Посчитай элементы",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["quiz", "geo"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["what_to_count", "correct_number", "tolerance"],
      "placeTypes": ["building", "monument", "square", "bridge"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "low",
      "short": "Посчитать колонны, арки, фонари, фигуры."
    },
    {
      "id": "find_odd_one",
      "num": 9,
      "name": "Найди лишний объект",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["quiz", "geo"],
      "difficulties": ["medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["candidates", "odd_id", "reason"],
      "placeTypes": ["square", "park", "ensemble"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "Указать элемент, который не из ансамбля или эпохи."
    },
    {
      "id": "viewpoint_photo",
      "num": 10,
      "name": "Фото-ракурс",
      "group": "visual",
      "uniqueFeature": false,
      "tags": ["cam", "geo"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": true,
      "needsAsset": ["required_anchors"],
      "placeTypes": ["viewpoint", "bridge", "embankment"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "Сделать кадр, где одновременно видны два якоря."
    },
    {
      "id": "word_from_facade",
      "num": 11,
      "name": "Слово с фасада",
      "group": "text",
      "uniqueFeature": false,
      "tags": ["quiz", "geo", "text"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["expected_word", "hint"],
      "placeTypes": ["building", "facade", "gate"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "low",
      "short": "Ввести слово, девиз или дату с фасада."
    },
    {
      "id": "anagram",
      "num": 12,
      "name": "Анаграмма места",
      "group": "text",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["letters", "answer"],
      "placeTypes": ["any"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "low",
      "short": "Собрать ключевое слово из букв подсказки."
    },
    {
      "id": "quote_detective",
      "num": 13,
      "name": "Цитата-детектив",
      "group": "text",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["quote", "target_place_id"],
      "placeTypes": ["monument", "building", "plaque"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "По цитате понять, к какому месту идти."
    },
    {
      "id": "year_key",
      "num": 14,
      "name": "Год-ключ",
      "group": "text",
      "uniqueFeature": false,
      "tags": ["quiz", "geo", "text"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["expected_year", "source_hint"],
      "placeTypes": ["plaque", "building", "monument"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "low",
      "short": "Найти год на объекте — он открывает следующую подсказку."
    },
    {
      "id": "decode_initials",
      "num": 15,
      "name": "Расшифруй инициалы",
      "group": "text",
      "uniqueFeature": false,
      "tags": ["quiz", "geo", "text"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["initials", "full_answer", "hints"],
      "placeTypes": ["plaque", "monument", "building"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "Расшифровать инициалы, общество или аббревиатуру."
    },
    {
      "id": "art_puzzle",
      "num": 16,
      "name": "Пазл картины / панно",
      "group": "puzzle",
      "uniqueFeature": false,
      "tags": ["quiz", "cam"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["puzzle_image", "piece_count"],
      "placeTypes": ["mural", "mosaic", "public_art"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "medium",
      "short": "Собрать цифровой пазл рядом с реальным произведением."
    },
    {
      "id": "route_cards",
      "num": 17,
      "name": "Собери маршрут из карточек",
      "group": "puzzle",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["medium"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["cards", "correct_order"],
      "placeTypes": ["any"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "Выстроить правильный порядок точек прогулки."
    },
    {
      "id": "restore_caption",
      "num": 18,
      "name": "Восстанови подпись",
      "group": "puzzle",
      "uniqueFeature": false,
      "tags": ["quiz", "geo", "text"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["caption_with_gaps", "answer"],
      "placeTypes": ["monument", "plaque", "public_art"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "low",
      "short": "Восстановить название или подпись с пропусками."
    },
    {
      "id": "fact_mosaic",
      "num": 19,
      "name": "Мозаика фактов",
      "group": "puzzle",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["facts", "targets"],
      "placeTypes": ["any"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "Привязать факты к фото или точкам."
    },
    {
      "id": "compass_quest",
      "num": 20,
      "name": "Компасный квест",
      "group": "space",
      "uniqueFeature": false,
      "tags": ["geo"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["bearing", "distance_m", "arrival_check"],
      "placeTypes": ["any"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "high",
      "short": "Идти по направлению и дистанции без точного пина."
    },
    {
      "id": "circle_object",
      "num": 21,
      "name": "Кольцо вокруг объекта",
      "group": "space",
      "uniqueFeature": false,
      "tags": ["geo"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["checkpoints"],
      "placeTypes": ["monument", "square", "park"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "Обойти объект и отметить несколько сторон/ракурсов."
    },
    {
      "id": "viewpoint_station",
      "num": 22,
      "name": "Видовая станция",
      "group": "space",
      "uniqueFeature": false,
      "tags": ["geo", "cam"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["viewpoint_coords", "what_is_visible"],
      "placeTypes": ["viewpoint", "bridge", "embankment", "park"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "low",
      "short": "Засчитаться только с конкретной видовой точки."
    },
    {
      "id": "quiet_courtyard",
      "num": 23,
      "name": "Тихий двор",
      "group": "space",
      "uniqueFeature": false,
      "tags": ["geo", "quiz"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["hidden_target", "hint_chain"],
      "placeTypes": ["courtyard", "arch", "lane"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "Найти скрытую деталь во дворе, арке или переулке."
    },
    {
      "id": "door_to_door",
      "num": 24,
      "name": "От двери до двери",
      "group": "space",
      "uniqueFeature": false,
      "tags": ["geo"],
      "difficulties": ["medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["ordered_stops", "mini_questions"],
      "placeTypes": ["building", "plaque", "street"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "Цепочка близких адресов строго по порядку."
    },
    {
      "id": "guess_role",
      "num": 25,
      "name": "Угадай роль героя",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz", "geo"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["options", "correct", "fact"],
      "placeTypes": ["monument", "plaque"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "low",
      "short": "Выбрать профессию/роль героя памятника."
    },
    {
      "id": "link_two_heroes",
      "num": 26,
      "name": "Свяжи двух героев",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["place_a", "place_b", "relation"],
      "placeTypes": ["monument", "plaque", "building"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "medium",
      "short": "Понять связь между двумя точками маршрута."
    },
    {
      "id": "era_style",
      "num": 27,
      "name": "Эпоха на ощупь",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz", "geo"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": true,
      "needsCamera": false,
      "needsAsset": ["style_options", "correct_style"],
      "placeTypes": ["building", "facade", "monument", "public_art"],
      "defaultEnabled": true,
      "mvp": false,
      "effort": "low",
      "short": "Определить стиль или эпоху объекта."
    },
    {
      "id": "myth_or_fact",
      "num": 28,
      "name": "Миф или факт",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["statements", "truth_map", "explanations"],
      "placeTypes": ["any"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "low",
      "short": "Отметить, что правда, а что городская легенда."
    },
    {
      "id": "sound_of_place",
      "num": 29,
      "name": "Звук места",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz", "geo", "audio"],
      "difficulties": ["easy", "medium"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["audio_clip", "options_or_target"],
      "placeTypes": ["monument", "theatre", "park", "street"],
      "defaultEnabled": false,
      "mvp": false,
      "effort": "medium",
      "short": "По аудиофрагменту выбрать или найти место."
    },
    {
      "id": "finale_synthesis",
      "num": 30,
      "name": "Финальный синтез",
      "group": "meaning",
      "uniqueFeature": false,
      "tags": ["quiz"],
      "difficulties": ["medium", "hard"],
      "needsOnSite": false,
      "needsCamera": false,
      "needsAsset": ["summary_question", "answer"],
      "placeTypes": ["any"],
      "defaultEnabled": true,
      "mvp": true,
      "effort": "low",
      "short": "Вопрос в финале, связывающий весь маршрут."
    }
  ]
}
;
