/**
 * Сюжет «Пушкин в Москве» v9
 * Невидимое письмо: 8 обрывков с уникальными краями → сборка на листе А4 → печать.
 */
window.STORY_ROUTES = window.STORY_ROUTES || {};

/** 8 частей одного письма. h — относительная высота на листе А4. edge — профиль нижнего края (верх следующего = тот же). */
window.KP_LETTER_PIECES = [
  {
    id: "p0",
    order: 0,
    h: 8,
    edge: "flat",
    text: "Москва — тебе, Александр.",
  },
  {
    id: "p1",
    order: 1,
    h: 13,
    edge: "zag-a",
    text: "За то, что жил среди нас и сделал нас слышнее себе —",
  },
  {
    id: "p2",
    order: 2,
    h: 12,
    edge: "zag-b",
    text: "за то, что улицы стали строками, а бульвары — паузой стиха,",
  },
  {
    id: "p3",
    order: 3,
    h: 16,
    edge: "zag-c",
    text: "мы благодарим. Ты вошёл в Москву — и Москва вошла в тебя:",
  },
  {
    id: "p4",
    order: 4,
    h: 14,
    edge: "zag-d",
    text: "смягчилась речь, ожила площадь, и бронза научилась дышать.",
  },
  {
    id: "p5",
    order: 5,
    h: 10,
    edge: "zag-e",
    text: "Мы изменили друг друга навеки.",
  },
  {
    id: "p6",
    order: 6,
    h: 15,
    edge: "zag-f",
    text: "А ныне взгляни иначе — не в лицо одно,",
  },
  {
    id: "p7",
    order: 7,
    h: 12,
    edge: "flat",
    text: "чуть сбоку: пусть печать ляжет на конверт.",
  },
];

window.STORY_ROUTES.pushkin = {
  id: "story-pushkin-moscow-v9",
  title: "Пушкин в Москве",
  subtitle: "Невидимое письмо: обрывки проступают там, где жили.",
  zone: "garden",
  zoneLabel: "Центр · Пушкин",
  difficulty: "story",
  difficultyLabel: "Сюжет",
  durationHint: "~90 мин",
  characterId: "pushkin",
  letterEra: true,
  mapBounds: {
    minLat: 55.7475,
    maxLat: 55.7675,
    minLon: 37.5865,
    maxLon: 37.6105,
  },
  chapters: [
    {
      slot: 1,
      chapterTitle: "Обращение",
      placeName: "Памятник А. С. Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "К бронзе",
      brief:
        "Друг мой, письмо невидимо, пока не встретишь бронзу в вышине —\nсовмести красный контур с фигурой: пусть плечи лягут на черте.",
      hintL1: "Не всадник и не сидящий: стоит на высоком камне, в сюртуке.",
      hintL2: "Рука у борта. Совпадите плечи и голову с красной линией.",
      hintL3: "Отойдите на восемь–двенадцать шагов: в кадр — вся фигура и постамент.",
      ui: "contour",
      silhouetteKey: "pushkin",
      skipGuess: true,
      matchMinScore: 0.86,
      contourHint: "Фигура сверху, постамент снизу — как в старинном силуэте.",
      fallbackQuestion: "Рука в борту сюртука?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "А чья рука сей образ высекла из векового камня?",
    },
    {
      slot: 2,
      chapterTitle: "Почерк",
      placeName: "Памятник А. С. Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Скульптор",
      mechanicId: "sculptor_name",
      title: "Чей резец",
      brief:
        "Не поэт здесь главная тайна и не заказчик площади шумной —\nназови фамилию мастера, что высек фигуру для площади юной.",
      hintL1: "Ищи не стих, а фамилию скульптора XIX века.",
      hintL2: "Русский мастер. Фамилия начинается на «О».",
      hintL3: "Опекушин.",
      ui: "input",
      expected: "опекушин",
      alternatives: ["Опекушин", "опекушина", "Александр Опекушин"],
      safePrompt: "Фамилия",
      radiusM: 40,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "По Тверскому бульвару — туда, где время говорит тихо.",
    },
    {
      slot: 3,
      chapterTitle: "Циферблат",
      placeName: "Тверской бульвар",
      address: "к Никитским воротам",
      lat: 55.7608,
      lon: 37.6015,
      mechanicName: "Год на циферблате",
      mechanicId: "plaque_scan",
      title: "Время на бульваре",
      brief:
        "Иди бульваром, где часы молчат, а год шепчет лишь тому, кто рядом.\nКогда кристалл зажжётся — открой замок у циферблата.",
      clueImage: "assets/maps/tverskoy-clock.jpg",
      hideClueOnTask: true,
      hintL1: "К Никитским воротам. Циферблат на бульваре подскажет год.",
      hintL2: "Конец восемнадцатого столетия.",
      hintL3: "1792.",
      ui: "geo",
      safeType: "year",
      safeCode: "1792",
      safePrompt: "",
      expected: "1792",
      radiusM: 45,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "Дальше — храм Большого Вознесения, где клятва стала судьбой.",
    },
    {
      slot: 4,
      chapterTitle: "Клятва",
      placeName: "Большое Вознесение",
      address: "пл. Никитские Ворота",
      lat: 55.7578,
      lon: 37.5975,
      mechanicName: "Шифр-диск",
      mechanicId: "geo_safe",
      title: "Круг венца",
      brief:
        "У храма клятвы круг замкни: день, месяц, год — три числа на диске.\nТам, где венчались некогда, любовь вписалась в каменный список.",
      hintL1: "С улицы у Большого Вознесения — внутрь храма входить не нужно.",
      hintL2: "День · месяц · две цифры года свадьбы с Натальей.",
      hintL3: "18 · 2 · 31.",
      ui: "geo",
      safeType: "dial",
      safeCode: "18-2-31",
      safePrompt: "",
      radiusM: 40,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "По Большой Никитской — слово на камне обратит буквы в числа.",
    },
    {
      slot: 5,
      chapterTitle: "Шифр",
      placeName: "Большая Никитская",
      address: "салонный след",
      lat: 55.7572,
      lon: 37.5958,
      mechanicName: "Слово → код",
      mechanicId: "word_from_facade",
      title: "Буквы в число",
      brief:
        "На фасаде — слово-ключ: каждую букву в число обрати.\nА — единица, далее по ряду; слитно цифры в сейф внеси.",
      hintL1: "Камень или лепнина — не вывеска лавки.",
      hintL2: "А=1 … Я=33. Ё считай как Е. Без пробелов.",
      hintL3: "ДОМ → 51614.",
      ui: "safe",
      safeType: "code",
      safeCode: "51614",
      safePrompt: "Код",
      expected: "51614",
      radiusM: 40,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "Арбат, дом пятьдесят третий — порог, где жили строки.",
    },
    {
      slot: 6,
      chapterTitle: "Порог",
      placeName: "Арбат, 53",
      address: "Мемориальная квартира Пушкина",
      lat: 55.7495,
      lon: 37.5908,
      mechanicName: "Ручка",
      mechanicId: "geo_safe",
      title: "Три оборота",
      brief:
        "Подойди к дому пятьдесят три: когда кристалл добела горит —\nтрижды полных оборота ручки — и порог письмо отворит.",
      hintL1: "Деревянный дом, номер пятьдесят три.",
      hintL2: "Ближе шагов на двадцать — кристалл почти бел.",
      hintL3: "Три полных оборота ручки сейфа.",
      ui: "geo",
      safeType: "wheel",
      safePrompt: "",
      radiusM: 35,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "В переулок у дома — тихая деталь чугунной речи.",
    },
    {
      slot: 7,
      chapterTitle: "Сноска",
      placeName: "Арбат · переулок",
      address: "у дома Пушкина",
      lat: 55.7490,
      lon: 37.5895,
      mechanicName: "Деталь",
      mechanicId: "find_detail",
      title: "Чугунная речь",
      brief:
        "Сверни с шума Арбата в боковой проход у дома-музея —\nнайди чугун иль лепнину; одно слово впиши — что видишь, то и есть ответ.",
      hintL1: "У дома-музея сверните с Арбата в тихий проход.",
      hintL2: "Чугун ограды или лепнина — не неон и не вывеска.",
      hintL3: "«решётка» или «лепнина».",
      ui: "input",
      expected: "решетка",
      alternatives: ["решётка", "лепнина", "фрагмент", "решетка", "чугун", "ограда"],
      safePrompt: "Слово",
      radiusM: 40,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "К Никитским — назови имя до венца, не после.",
    },
    {
      slot: 8,
      chapterTitle: "Имя",
      placeName: "Никитские ворота",
      address: "площадь венчания",
      lat: 55.7578,
      lon: 37.5975,
      mechanicName: "Фамилия",
      mechanicId: "bride_name",
      title: "До венца",
      brief:
        "До венца — иное имя. Не Пушкина — иное звучанье.\nФамилия невесты на «Г» — впиши в письмо признанье.",
      hintL1: "Не замужняя фамилия — та, что была до свадьбы.",
      hintL2: "Знаменитый московский род. Начинается на «Г».",
      hintL3: "Гончарова.",
      ui: "input",
      expected: "гончарова",
      alternatives: ["Гончарова", "Наталья Гончарова", "Гончаровой"],
      safePrompt: "Фамилия",
      radiusM: 40,
      revealM: 150,
      awardsScrap: true,
      fact: "",
      unlockedText: "У бронзы собери обрывки на листе — края подскажут место.",
    },
    {
      slot: 9,
      chapterTitle: "Сборка",
      placeName: "Памятник Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Письмо-пазл",
      mechanicId: "letter_assemble",
      title: "Лист письма",
      brief: "",
      hintL1: "Края обрывков совпадают, как рваная бумага.",
      hintL2: "Верхний кусок начинается с «Москва — тебе».",
      hintL3: "Нижний зовёт взглянуть «чуть сбоку».",
      ui: "letter_puzzle",
      radiusM: 45,
      revealM: 150,
      fact: "Письмо цельно. Москва и поэт узнали друг друга — пора взглянуть сбоку.",
      unlockedText: "Совмести контур сбоку — печать на конверт.",
    },
    {
      slot: 10,
      chapterTitle: "Печать",
      placeName: "Памятник Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "Иной взгляд",
      brief:
        "Письмо просит иначе: не анфас — чуть сбоку, в три четверти.\nСовмести контур — и печать ляжет на конверт.",
      hintL1: "Полшага вбок от центра площади.",
      hintL2: "Тот же постамент, иная линия плеч.",
      hintL3: "Красная линия на бронзе сбоку — конверт закрыт.",
      ui: "contour",
      silhouetteKey: "pushkin_side",
      skipGuess: true,
      matchMinScore: 0.84,
      contourHint: "Ракурс три четверти: чуть сбоку от лица.",
      fallbackQuestion: "Стоящий поэт на высоком постаменте?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 150,
      fact: "Конверт запечатан. Невидимое письмо прочитано — и снова стало воздухом Москвы.",
      unlockedText: "Прогулка окончена. Храни строки.",
    },
  ],
};
