/**
 * Сюжет «Пушкин в Москве» v6
 * Сквозное «Невидимое письмо». Без дублей дат: 1880 и 1831 — только по одному разу.
 */
window.STORY_ROUTES = window.STORY_ROUTES || {};

window.STORY_ROUTES.pushkin = {
  id: "story-pushkin-moscow-v6",
  title: "Пушкин в Москве",
  subtitle: "Невидимое письмо Москвы: от бронзы к дому.",
  zone: "garden",
  zoneLabel: "Центр · Пушкин",
  difficulty: "story",
  difficultyLabel: "Сюжет",
  durationHint: "~90 мин",
  characterId: "pushkin",
  mapBounds: {
    minLat: 55.7475,
    maxLat: 55.7675,
    minLon: 37.5865,
    maxLon: 37.6105,
  },
  chapters: [
    {
      slot: 1,
      chapterTitle: "Обращение",
      placeName: "Памятник А. С. Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "Силуэт",
      brief: "Совместите красный контур с памятником — лицом к нему, с площади.",
      hintL1: "Высокий постамент, стоящая фигура в сюртуке — не всадник и не сидящий.",
      hintL2: "Рука у борта сюртука. Совпадите плечи с красной линией.",
      hintL3: "Отойдите на 8–12 шагов: в кадр — фигура и весь постамент.",
      ui: "contour",
      silhouetteKey: "pushkin",
      skipGuess: true,
      matchMinScore: 0.86,
      contourHint: "Фигура сверху, постамент снизу.",
      fallbackQuestion: "Рука в борту сюртука?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 150,
      fact: "Контур принят.",
      unlockedText: "Дальше — чья рука высекла бронзу.",
    },
    {
      slot: 2,
      chapterTitle: "Почерк",
      placeName: "Памятник А. С. Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Скульптор",
      mechanicId: "sculptor_name",
      title: "Чей почерк",
      brief: "Введите фамилию скульптора этого памятника.",
      hintL1: "Не поэт и не заказчик — мастер, что высек фигуру для площади.",
      hintL2: "Русский скульптор XIX века. Фамилия на «О».",
      hintL3: "Опекушин.",
      ui: "input",
      expected: "опекушин",
      alternatives: ["Опекушин", "опекушина", "Александр Опекушин"],
      safePrompt: "Фамилия",
      radiusM: 40,
      revealM: 150,
      fact: "Александр Опекушин. Открытие памятника — 1880.",
      unlockedText: "По Тверскому бульвару — к циферблату.",
    },
    {
      slot: 3,
      chapterTitle: "Циферблат",
      placeName: "Тверской бульвар",
      address: "к Никитским воротам",
      lat: 55.7608,
      lon: 37.6015,
      mechanicName: "Год на циферблате",
      mechanicId: "plaque_scan",
      title: "Четыре цифры",
      brief: "У циферблата на бульваре. Когда кристалл загорится — наберите год на барабанах.",
      clueImage: "assets/maps/tverskoy-clock.jpg",
      hintL1: "Идите по бульвару к Никитским. Циферблат — подсказка к году.",
      hintL2: "Четыре цифры конца XVIII века.",
      hintL3: "1792.",
      ui: "geo",
      safeType: "year",
      safeCode: "1792",
      safePrompt: "Год",
      expected: "1792",
      radiusM: 45,
      revealM: 150,
      fact: "Год с циферблата принят.",
      unlockedText: "Дальше — храм Большого Вознесения.",
    },
    {
      slot: 4,
      chapterTitle: "Клятва",
      placeName: "Большое Вознесение",
      address: "пл. Никитские Ворота",
      lat: 55.7578,
      lon: 37.5975,
      mechanicName: "Шифр-диск",
      mechanicId: "geo_safe",
      title: "Дата венчания",
      brief: "У храма, когда кристалл ярко загорится — наберите на диске день · месяц · год венчания.",
      hintL1: "С улицы у Большого Вознесения, не заходя внутрь.",
      hintL2: "День · месяц · две цифры года свадьбы с Гончаровой.",
      hintL3: "18 · 2 · 31.",
      ui: "geo",
      safeType: "dial",
      safeCode: "18-2-31",
      safePrompt: "День · месяц · год",
      radiusM: 40,
      revealM: 150,
      fact: "18 февраля 1831 — венчание здесь.",
      unlockedText: "По Большой Никитской — слово на фасаде.",
    },
    {
      slot: 5,
      chapterTitle: "Шифр",
      placeName: "Большая Никитская",
      address: "салонный след",
      lat: 55.7572,
      lon: 37.5958,
      mechanicName: "Слово → код",
      mechanicId: "word_from_facade",
      title: "Буквы в число",
      brief: "Слово с фасада: каждая буква → номер в алфавите (А=1). Введите цифры слитно.",
      hintL1: "Камень или лепнина — не вывеска магазина.",
      hintL2: "А=1 … Я=33. Ё как Е. Без пробелов.",
      hintL3: "ДОМ → 51614.",
      ui: "safe",
      safeType: "code",
      safeCode: "51614",
      safePrompt: "Код",
      expected: "51614",
      radiusM: 40,
      revealM: 150,
      fact: "Код принят.",
      unlockedText: "Арбат, 53.",
    },
    {
      slot: 6,
      chapterTitle: "Порог",
      placeName: "Арбат, 53",
      address: "Мемориальная квартира Пушкина",
      lat: 55.7495,
      lon: 37.5908,
      mechanicName: "Ручка",
      mechanicId: "geo_safe",
      title: "Дом",
      brief: "Подойдите к дому 53. Когда кристалл на максимуме — три полных оборота ручки сейфа.",
      hintL1: "Деревянный дом, номер 53.",
      hintL2: "Ближе ~20 м — кристалл почти добела.",
      hintL3: "Три полных оборота ручки.",
      ui: "geo",
      safeType: "wheel",
      safePrompt: "Три оборота",
      radiusM: 35,
      revealM: 150,
      fact: "Порог открыт.",
      unlockedText: "В переулок у дома — тихая деталь.",
    },
    {
      slot: 7,
      chapterTitle: "Сноска",
      placeName: "Арбат · переулок",
      address: "у дома Пушкина",
      lat: 55.7490,
      lon: 37.5895,
      mechanicName: "Деталь",
      mechanicId: "find_detail",
      title: "Одно слово",
      brief: "В боковом проходе найдите чугун или лепнину. Введите, что увидели.",
      hintL1: "Сверните с Арбата у дома-музея.",
      hintL2: "Чугун ограды или лепнина — не неон.",
      hintL3: "«решётка» или «лепнина».",
      ui: "input",
      expected: "решетка",
      alternatives: ["решётка", "лепнина", "фрагмент", "решетка", "чугун", "ограда"],
      safePrompt: "Слово",
      radiusM: 40,
      revealM: 150,
      fact: "Деталь принята.",
      unlockedText: "К Никитским — фамилия невесты.",
    },
    {
      slot: 8,
      chapterTitle: "Имя",
      placeName: "Никитские ворота",
      address: "площадь венчания",
      lat: 55.7578,
      lon: 37.5975,
      mechanicName: "Фамилия",
      mechanicId: "bride_name",
      title: "До венца",
      brief: "Введите девичью фамилию Натальи — той, с кем венчались у этого храма.",
      hintL1: "Не Пушкина — фамилия до свадьбы.",
      hintL2: "Знаменитый московский род. На «Г».",
      hintL3: "Гончарова.",
      ui: "input",
      expected: "гончарова",
      alternatives: ["Гончарова", "Наталья Гончарова", "Гончаровой"],
      safePrompt: "Фамилия",
      radiusM: 40,
      revealM: 150,
      fact: "Наталья Гончарова.",
      unlockedText: "К памятнику — финальный ракурс.",
    },
    {
      slot: 9,
      chapterTitle: "Конверт",
      placeName: "Памятник Пушкину",
      address: "Пушкинская площадь",
      lat: 55.76528,
      lon: 37.60583,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "Иной взгляд",
      brief: "Снова у памятника. Совместите контур сбоку (¾) — не анфас.",
      hintL1: "Полшага вбок от центра площади.",
      hintL2: "Тот же постамент, иная линия плеч.",
      hintL3: "Красная линия на бронзе сбоку — готово.",
      ui: "contour",
      silhouetteKey: "pushkin_side",
      skipGuess: true,
      matchMinScore: 0.84,
      contourHint: "Ракурс ¾: чуть сбоку.",
      fallbackQuestion: "Стоящий поэт на высоком постаменте?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 150,
      fact: "Письмо закрыто.",
      unlockedText: "Прогулка окончена.",
    },
  ],
};
