/**
 * Сюжет «Гоголь в Москве» v1
 * Две тени: двойник на Никитском и зимняя мистика города.
 */
window.STORY_ROUTES = window.STORY_ROUTES || {};

window.STORY_ROUTES.gogol = {
  id: "story-gogol-moscow-v1",
  title: "Гоголь в Москве",
  subtitle: "Две тени на Никитском: город двойников и чернильных клякс.",
  zone: "garden",
  zoneLabel: "Никитский · Гоголь",
  difficulty: "story",
  difficultyLabel: "Сюжет",
  durationHint: "~70 мин",
  characterId: "gogol",
  letterEra: false,
  mapBounds: {
    minLat: 55.752,
    maxLat: 55.762,
    minLon: 37.592,
    maxLon: 37.608,
  },
  chapters: [
    {
      slot: 1,
      chapterTitle: "Сидящий",
      placeName: "Памятник Н. В. Гоголю",
      address: "Никитский бульвар",
      lat: 55.7574,
      lon: 37.5989,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "Тень в кресле",
      brief:
        "Сидящий, усталый, будто только что закрыл рукопись.\nСовмести контур с этой тенью.",
      hintL1: "Не стоячий монумент — сидит.",
      hintL2: "Плащ, наклонённая голова.",
      hintL3: "Отойдите: в кадр — фигура целиком.",
      ui: "contour",
      silhouetteKey: "gogol",
      skipGuess: true,
      matchMinScore: 0.84,
      contourHint: "Сидящая фигура в плаще.",
      fallbackQuestion: "Памятник сидячий?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 140,
      fact: "Андреевский Гоголь — «трагический»: город долго спорил, какой образ вернее.",
      unlockedText: "У этого бульвара две бронзы. Найди вторую тень.",
    },
    {
      slot: 2,
      chapterTitle: "Двойник",
      placeName: "Двор дома Гоголя",
      address: "Никитский бульвар, у музея",
      lat: 55.75715,
      lon: 37.59935,
      mechanicName: "Код",
      mechanicId: "year_key",
      title: "Две бронзы",
      brief:
        "Москва держит два образа Гоголя — стоячий и сидячий.\nКод сейфа: ТЕНЬ.",
      hintL1: "То, что отбрасывает двойник.",
      hintL2: "Четыре буквы.",
      hintL3: "ТЕНЬ.",
      ui: "safe",
      safeType: "code",
      safeCode: "ТЕНЬ",
      safePrompt: "Код двойника",
      expected: "ТЕНЬ",
      radiusM: 45,
      revealM: 140,
      fact: "Стоячий Гоголь (Томский) и сидячий (Андреев) — два взгляда города на одного человека.",
      unlockedText: "В дом на бульваре — где догорали рукописи.",
    },
    {
      slot: 3,
      chapterTitle: "Дом",
      placeName: "Дом Н. В. Гоголя",
      address: "Никитский бульвар, 7а (музей)",
      lat: 55.75705,
      lon: 37.59955,
      mechanicName: "Год",
      mechanicId: "year_key",
      title: "1852",
      brief: "Здесь прошли последние дни. Год ухода — на барабанах.",
      hintL1: "Середина XIX века.",
      hintL2: "1852.",
      hintL3: "1852.",
      ui: "safe",
      safeType: "year",
      safeCode: "1852",
      safePrompt: "Год",
      expected: "1852",
      radiusM: 40,
      revealM: 140,
      fact: "В этом доме Гоголь жил у Толстых; здесь сожжены главы «Мёртвых душ».",
      unlockedText: "К Никитским воротам — ротонда и городской свет.",
    },
    {
      slot: 4,
      chapterTitle: "Ворота",
      placeName: "Никитские ворота · ротонда",
      address: "площадь Никитские Ворота",
      lat: 55.75778,
      lon: 37.5958,
      mechanicName: "Гео",
      mechanicId: "geo_safe",
      title: "Шинель города",
      brief:
        "У ротонды город надевает шинель.\nКогда кристалл загорится — введи: ШИНЕЛЬ.",
      hintL1: "Повесть о шинели — одно слово.",
      hintL2: "Ш…",
      hintL3: "ШИНЕЛЬ.",
      ui: "geo",
      safeType: "code",
      safeCode: "ШИНЕЛЬ",
      safePrompt: "Слово повести",
      expected: "ШИНЕЛЬ",
      radiusM: 50,
      revealM: 140,
      fact: "«Шинель» — петербургская повесть, но Москва Гоголя тоже умеет холодеть.",
      unlockedText: "Чёрт из Диканьки выглядывает с Тверского — шутка города.",
    },
    {
      slot: 5,
      chapterTitle: "Диканька",
      placeName: "Тверской бульвар",
      address: "у начала бульвара / к Никитским",
      lat: 55.7589,
      lon: 37.5978,
      mechanicName: "Роль",
      mechanicId: "guess_role",
      title: "Вечера",
      brief:
        "Какой цикл открывает гоголевскую мистику деревни и ночи?\nКлюч: ДИКАНЬКА.",
      hintL1: "«Вечера на хуторе близ…»",
      hintL2: "Диканька.",
      hintL3: "ДИКАНЬКА.",
      ui: "input",
      expected: "диканька",
      alternatives: ["Диканька", "ДИКАНЬКА", "Вечера на хуторе близ Диканьки"],
      safePrompt: "Название",
      radiusM: 50,
      revealM: 140,
      fact: "Диканька — не Москва, но её снег и чёрт давно живут в воображении столицы.",
      unlockedText: "Финал у сидящей тени: одно слово — НОС.",
    },
    {
      slot: 6,
      chapterTitle: "Нос",
      placeName: "Памятник Н. В. Гоголю",
      address: "Никитский бульвар",
      lat: 55.7574,
      lon: 37.5989,
      mechanicName: "Финал",
      mechanicId: "finale_synthesis",
      title: "Убежавшая деталь",
      brief: "Собери абсурд города в слово-ключ: НОС.",
      hintL1: "Повесть, где деталь сбежала сама.",
      hintL2: "Три буквы.",
      hintL3: "НОС.",
      ui: "input",
      expected: "нос",
      alternatives: ["НОС", "Нос"],
      safePrompt: "Слово-финал",
      radiusM: 45,
      revealM: 140,
      fact: "Две бронзы, одна шинель, один нос — Москва Гоголя любит двойников.",
      unlockedText: "Снег ещё падает. Тень остаётся на бульваре.",
    },
  ],
};
