/**
 * Сюжет «Гоголь в Москве» v2
 * Две тени + письмо Москвы.
 */
window.STORY_ROUTES = window.STORY_ROUTES || {};

window.STORY_ROUTES.gogol = {
  id: "story-gogol-moscow-v2",
  title: "Гоголь в Москве",
  subtitle: "Две тени: Москва пишет тебе обрывками шинели.",
  zone: "garden",
  zoneLabel: "Никитский · Гоголь",
  difficulty: "story",
  difficultyLabel: "Сюжет",
  durationHint: "~75 мин",
  characterId: "gogol",
  letterEra: true,
  mapBounds: {
    minLat: 55.752,
    maxLat: 55.762,
    minLon: 37.592,
    maxLon: 37.608,
  },
  chapters: [
    {
      slot: 1,
      chapterTitle: "Сидящий",
      placeName: "Памятник Н. В. Гоголю",
      address: "Никитский бульвар",
      lat: 55.7574,
      lon: 37.5989,
      mechanicName: "Контур",
      mechanicId: "contour_camera",
      title: "Тень в кресле",
      brief:
        "Одна из двух московских бронз — усталая, будто после рукописи.\nСовмести контур с этой тенью.",
      hintL1: "Не стоячий монумент — поза отдыха / усталости.",
      hintL2: "Плащ, наклон головы — «трагический» образ бульвара.",
      hintL3: "Отойдите: в кадр — вся фигура, не только лицо.",
      ui: "contour",
      silhouetteKey: "gogol",
      skipGuess: true,
      matchMinScore: 0.84,
      contourHint: "Сидящая фигура в плаще.",
      fallbackQuestion: "Сидит ли фигура?",
      fallbackAnswer: "да",
      radiusM: 45,
      revealM: 140,
      awardsScrap: true,
      fact: "",
      unlockedText: "У бульвара две бронзы. Код — то, что отбрасывает двойник.",
    },
    {
      slot: 2,
      chapterTitle: "Двойник",
      placeName: "Двор дома Гоголя",
      address: "Никитский бульвар, у музея",
      lat: 55.75715,
      lon: 37.59935,
      mechanicName: "Код",
      mechanicId: "year_key",
      title: "Две бронзы",
      brief:
        "Москва держит два образа одного человека.\nКод сейфа — четыре буквы: то, без чего двойник невозможен.",
      hintL1: "Не «двойник» и не «бронза» — короче и темнее.",
      hintL2: "То, что стелется за спиной при свете фонаря.",
      hintL3: "В письме позже будет: «оставил нам две…» — однокоренное слово.",
      ui: "safe",
      safeType: "code",
      safeCode: "ТЕНЬ",
      safePrompt: "Код",
      expected: "ТЕНЬ",
      radiusM: 45,
      revealM: 140,
      awardsScrap: true,
      fact: "",
      unlockedText: "В дом на бульваре — год, когда здесь погасли последние дни.",
    },
    {
      slot: 3,
      chapterTitle: "Дом",
      placeName: "Дом Н. В. Гоголя",
      address: "Никитский бульвар, 7а (музей)",
      lat: 55.75705,
      lon: 37.59955,
      mechanicName: "Год",
      mechanicId: "year_key",
      title: "Последний год",
      brief: "Здесь прошли последние дни. Год ухода — на барабанах.",
      hintL1: "Середина XIX века — не путать с годом «Мёртвых душ» в печати.",
      hintL2: "После сожжения глав; зима, Москва, дом на Никитском.",
      hintL3: "Четыре цифры: восемьсот пятьдесят… второй.",
      ui: "safe",
      safeType: "year",
      safeCode: "1852",
      safePrompt: "Год",
      expected: "1852",
      radiusM: 40,
      revealM: 140,
      awardsScrap: true,
      fact: "",
      unlockedText: "К ротонде — город надевает то, что греет бедняка из повести.",
    },
    {
      slot: 4,
      chapterTitle: "Ворота",
      placeName: "Никитские ворота · ротонда",
      address: "площадь Никитские Ворота",
      lat: 55.75778,
      lon: 37.5958,
      mechanicName: "Гео",
      mechanicId: "geo_safe",
      title: "То, что греет",
      brief:
        "У ротонды, когда кристалл бел — введи слово повести\nо вещи, без которой герой мёрзнет и в прямом, и в переносном смысле.",
      hintL1: "Не сапоги и не шапка — верхняя одежда из названия.",
      hintL2: "Шесть букв. Акакий Акакиевич знал её цену.",
      hintL3: "Петербургская повесть, но холод её знаком и Москве.",
      ui: "geo",
      safeType: "code",
      safeCode: "ШИНЕЛЬ",
      safePrompt: "Слово",
      expected: "ШИНЕЛЬ",
      radiusM: 50,
      revealM: 140,
      awardsScrap: true,
      fact: "",
      unlockedText: "Вечера у хутора: какое имя ночи и снега в цикле?",
    },
    {
      slot: 5,
      chapterTitle: "Диканька",
      placeName: "Тверской бульвар",
      address: "у начала бульвара / к Никитским",
      lat: 55.7589,
      lon: 37.5978,
      mechanicName: "Роль",
      mechanicId: "guess_role",
      title: "Вечера",
      brief:
        "Какой топоним открывает цикл вечеров — деревня, хутор, ночь и чёрт?",
      hintL1: "«Вечера на хуторе близ…» — одно слово-продолжение.",
      hintL2: "Звучит по-малороссийски; в Москве стало нарицательным для снежной мистики.",
      hintL3: "Не «хутор» и не «вечера» — имя места в заголовке.",
      ui: "input",
      expected: "диканька",
      alternatives: ["Диканька", "ДИКАНЬКА", "Вечера на хуторе близ Диканьки"],
      safePrompt: "Имя",
      radiusM: 50,
      revealM: 140,
      awardsScrap: true,
      fact: "",
      unlockedText: "Сложи обрывки у сидящей тени — письмо не тает.",
    },
    {
      slot: 6,
      chapterTitle: "Письмо",
      placeName: "Памятник Н. В. Гоголю",
      address: "Никитский бульвар",
      lat: 55.7574,
      lon: 37.5989,
      mechanicName: "Письмо-пазл",
      mechanicId: "letter_assemble",
      title: "Лист шинели",
      brief: "Сложи рваные куски: края подскажут соседство.",
      hintL1: "Слева вверху — «Николай Васильевич!»",
      hintL2: "Стыки совпадают, как две тени на одном снегу.",
      hintL3: "Внизу — «благодарим шёпотом» и падающий снег.",
      ui: "letter_puzzle",
      radiusM: 45,
      revealM: 140,
      awardsScrap: false,
      fact: "",
      unlockedText: "Письмо собрано. Снег ещё падает.",
    },
  ],
};
